//! SQLite persistence layer.
//!
//! All database access goes through this module. Functions in this file are
//! intentionally low-level: they take/return domain types from
//! [`crate::models`] and translate to/from SQLite rows. They do not know
//! about app state, broadcast channels, or LLM behavior.
//!
//! Sequence numbers (`room_events.sequence`, `room_reports.sequence`) are
//! generated by callers (the orchestrator owns an in-memory counter per
//! room). On orchestrator startup, [`max_event_sequence`] and
//! [`max_report_sequence`] seed those counters.

use crate::models::{
  ProviderConfig, ReportStatus, Room, RoomEvent, RoomEventKind, RoomReport,
  RoomStatus,
};
use anyhow::{Context, Result};
use chrono::{DateTime, Utc};
use sqlx::Row;
use sqlx::sqlite::{
  SqliteConnectOptions, SqliteJournalMode, SqlitePoolOptions,
};
use sqlx::{SqlitePool, sqlite::SqliteRow};
use uuid::Uuid;

// -- Pool ------------------------------------------------------------------

/// Opens (or creates) the SQLite database, runs migrations, and returns the
/// pool. The pool's max connection count is small because all writes
/// originate from the orchestrator and a handful of API handlers.
pub async fn init_pool(database_url: &str) -> Result<SqlitePool> {
  let options = database_url
    .parse::<SqliteConnectOptions>()
    .context("invalid DATABASE_URL")?
    .journal_mode(SqliteJournalMode::Wal)
    .foreign_keys(true)
    .create_if_missing(true);

  let pool = SqlitePoolOptions::new()
    .max_connections(5)
    .connect_with(options)
    .await
    .context("failed to connect to SQLite database")?;

  sqlx::migrate!("./migrations")
    .run(&pool)
    .await
    .context("failed to run database migrations")?;

  Ok(pool)
}

// -- Rooms -----------------------------------------------------------------

/// Inserts a new room. Fails if a room with the same `slug` already exists.
pub async fn insert_room(pool: &SqlitePool, room: &Room) -> Result<()> {
  let low_json = serde_json::to_string(&room.low)
    .context("failed to encode low provider config")?;
  let high_json = serde_json::to_string(&room.high)
    .context("failed to encode high provider config")?;

  sqlx::query(
    "INSERT INTO rooms (
        id, name, slug, topic, goal, instruction, background, status,
        chat_interval_seconds, evaluation_interval_seconds,
        report_interval_seconds, python_timeout_seconds,
        python_feedback_every, auto_pause_when_converged,
        resume_schedule_cron, resume_schedule_label,
        low_provider_config, high_provider_config, created_at, updated_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
  )
  .bind(room.id.to_string())
  .bind(&room.name)
  .bind(&room.slug)
  .bind(&room.topic)
  .bind(&room.goal)
  .bind(room.instruction.as_deref())
  .bind(room.background.as_deref())
  .bind(room.status.as_str())
  .bind(room.chat_interval_seconds as i64)
  .bind(room.evaluation_interval_seconds as i64)
  .bind(room.report_interval_seconds as i64)
  .bind(room.python_timeout_seconds as i64)
  .bind(room.python_feedback_every as i64)
  .bind(room.auto_pause_when_converged)
  .bind(&room.resume_schedule_cron)
  .bind(&room.resume_schedule_label)
  .bind(&low_json)
  .bind(&high_json)
  .bind(room.created_at.to_rfc3339())
  .bind(room.updated_at.to_rfc3339())
  .execute(pool)
  .await
  .context("failed to insert room")?;

  Ok(())
}

/// Replaces every mutable field of an existing room. The orchestrator does
/// not call this directly — only the `PATCH /v1/rooms/:id` handler does.
pub async fn update_room(pool: &SqlitePool, room: &Room) -> Result<()> {
  let low_json = serde_json::to_string(&room.low)
    .context("failed to encode low provider config")?;
  let high_json = serde_json::to_string(&room.high)
    .context("failed to encode high provider config")?;

  sqlx::query(
    "UPDATE rooms SET
        name = ?, slug = ?, topic = ?, goal = ?, instruction = ?,
        background = ?, status = ?, chat_interval_seconds = ?,
        evaluation_interval_seconds = ?, report_interval_seconds = ?,
        python_timeout_seconds = ?, python_feedback_every = ?,
        auto_pause_when_converged = ?, resume_schedule_cron = ?,
        resume_schedule_label = ?, low_provider_config = ?,
        high_provider_config = ?, updated_at = ?
     WHERE id = ?",
  )
  .bind(&room.name)
  .bind(&room.slug)
  .bind(&room.topic)
  .bind(&room.goal)
  .bind(room.instruction.as_deref())
  .bind(room.background.as_deref())
  .bind(room.status.as_str())
  .bind(room.chat_interval_seconds as i64)
  .bind(room.evaluation_interval_seconds as i64)
  .bind(room.report_interval_seconds as i64)
  .bind(room.python_timeout_seconds as i64)
  .bind(room.python_feedback_every as i64)
  .bind(room.auto_pause_when_converged)
  .bind(&room.resume_schedule_cron)
  .bind(&room.resume_schedule_label)
  .bind(&low_json)
  .bind(&high_json)
  .bind(room.updated_at.to_rfc3339())
  .bind(room.id.to_string())
  .execute(pool)
  .await
  .context("failed to update room")?;

  Ok(())
}

/// Updates only `status` and `updated_at`. Fast-path used by the orchestrator
/// when pausing/resuming/failing a room.
pub async fn update_room_status(
  pool: &SqlitePool,
  room_id: Uuid,
  status: RoomStatus,
  updated_at: DateTime<Utc>,
) -> Result<()> {
  sqlx::query("UPDATE rooms SET status = ?, updated_at = ? WHERE id = ?")
    .bind(status.as_str())
    .bind(updated_at.to_rfc3339())
    .bind(room_id.to_string())
    .execute(pool)
    .await
    .context("failed to update room status")?;
  Ok(())
}

/// Deletes a room and all of its events/reports (FK cascade).
pub async fn delete_room(pool: &SqlitePool, room_id: Uuid) -> Result<()> {
  sqlx::query("DELETE FROM rooms WHERE id = ?")
    .bind(room_id.to_string())
    .execute(pool)
    .await
    .context("failed to delete room")?;
  Ok(())
}

pub async fn load_all_rooms(pool: &SqlitePool) -> Result<Vec<Room>> {
  let rows = sqlx::query("SELECT * FROM rooms ORDER BY created_at DESC")
    .fetch_all(pool)
    .await
    .context("failed to load rooms")?;

  rows.into_iter().map(parse_room_row).collect()
}

/// Returns true if the slug is already taken by some *other* room. Used by
/// the create/update handlers to surface a friendly conflict error.
pub async fn slug_taken(
  pool: &SqlitePool,
  slug: &str,
  exclude: Option<Uuid>,
) -> Result<bool> {
  let row = match exclude {
    Some(id) => sqlx::query(
      "SELECT 1 AS taken FROM rooms WHERE slug = ? AND id != ? LIMIT 1",
    )
    .bind(slug)
    .bind(id.to_string())
    .fetch_optional(pool)
    .await
    .context("failed to check slug uniqueness")?,
    None => sqlx::query("SELECT 1 AS taken FROM rooms WHERE slug = ? LIMIT 1")
      .bind(slug)
      .fetch_optional(pool)
      .await
      .context("failed to check slug uniqueness")?,
  };

  Ok(row.is_some())
}

fn parse_room_row(row: SqliteRow) -> Result<Room> {
  let id_str: String = row.try_get("id").context("rooms.id missing")?;
  let id: Uuid = id_str.parse().context("rooms.id not a uuid")?;

  let status_str: String =
    row.try_get("status").context("rooms.status missing")?;
  let status = RoomStatus::parse(&status_str)?;

  let low_json: String = row
    .try_get("low_provider_config")
    .context("rooms.low missing")?;
  let high_json: String = row
    .try_get("high_provider_config")
    .context("rooms.high missing")?;
  let low: ProviderConfig = serde_json::from_str(&low_json)
    .context("rooms.low_provider_config: invalid JSON")?;
  let high: ProviderConfig = serde_json::from_str(&high_json)
    .context("rooms.high_provider_config: invalid JSON")?;

  let chat_interval: i64 = row
    .try_get("chat_interval_seconds")
    .context("rooms.chat_interval_seconds missing")?;
  let eval_interval: i64 = row
    .try_get("evaluation_interval_seconds")
    .context("rooms.evaluation_interval_seconds missing")?;
  let report_interval: i64 = row
    .try_get("report_interval_seconds")
    .context("rooms.report_interval_seconds missing")?;
  let python_timeout: i64 = row
    .try_get("python_timeout_seconds")
    .context("rooms.python_timeout_seconds missing")?;
  let python_feedback: i64 = row
    .try_get("python_feedback_every")
    .context("rooms.python_feedback_every missing")?;
  let auto_pause_when_converged: bool = row
    .try_get("auto_pause_when_converged")
    .context("rooms.auto_pause_when_converged missing")?;
  let resume_schedule_cron: String = row
    .try_get("resume_schedule_cron")
    .context("rooms.resume_schedule_cron missing")?;
  let resume_schedule_label: String = row
    .try_get("resume_schedule_label")
    .context("rooms.resume_schedule_label missing")?;

  Ok(Room {
    id,
    name: row.try_get("name").context("rooms.name missing")?,
    slug: row.try_get("slug").context("rooms.slug missing")?,
    topic: row.try_get("topic").context("rooms.topic missing")?,
    goal: row.try_get("goal").context("rooms.goal missing")?,
    instruction: row
      .try_get("instruction")
      .context("rooms.instruction missing")?,
    background: row
      .try_get("background")
      .context("rooms.background missing")?,
    status,
    chat_interval_seconds: chat_interval as u64,
    evaluation_interval_seconds: eval_interval as u64,
    report_interval_seconds: report_interval as u64,
    python_timeout_seconds: python_timeout as u64,
    python_feedback_every: python_feedback as u32,
    auto_pause_when_converged,
    resume_schedule_cron,
    resume_schedule_label,
    low,
    high,
    created_at: parse_timestamp(&row, "created_at")?,
    updated_at: parse_timestamp(&row, "updated_at")?,
  })
}

// -- Events ----------------------------------------------------------------

/// Inserts one finalized message row. The caller is responsible for
/// populating `reasoning` (empty when none) and `tool_calls` (empty Vec
/// when none) so the schema stays uniform across kinds.
pub async fn insert_event(pool: &SqlitePool, event: &RoomEvent) -> Result<()> {
  let tool_calls_json = serde_json::to_string(&event.tool_calls)
    .context("failed to serialize tool_calls")?;
  sqlx::query(
    "INSERT INTO room_events
        (room_id, sequence, kind, agent, content, reasoning, tool_calls, timestamp)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
  )
  .bind(event.room_id.to_string())
  .bind(event.sequence as i64)
  .bind(event.kind.as_str())
  .bind(event.agent.as_deref())
  .bind(&event.content)
  .bind(&event.reasoning)
  .bind(tool_calls_json)
  .bind(event.timestamp.to_rfc3339())
  .execute(pool)
  .await
  .context("failed to insert room event")?;
  Ok(())
}

pub async fn load_room_events(
  pool: &SqlitePool,
  room_id: Uuid,
) -> Result<Vec<RoomEvent>> {
  let rows = sqlx::query(
    "SELECT room_id, sequence, kind, agent, content, reasoning, tool_calls, timestamp
     FROM room_events
     WHERE room_id = ?
     ORDER BY sequence ASC",
  )
  .bind(room_id.to_string())
  .fetch_all(pool)
  .await
  .context("failed to load room events")?;

  rows.into_iter().map(parse_event_row).collect()
}

/// Returns the highest `sequence` for the given room, or 0 if the room has
/// no events yet. Used to seed the orchestrator's per-room counter on
/// startup.
pub async fn max_event_sequence(
  pool: &SqlitePool,
  room_id: Uuid,
) -> Result<u64> {
  let row = sqlx::query(
    "SELECT COALESCE(MAX(sequence), 0) AS max_seq
     FROM room_events WHERE room_id = ?",
  )
  .bind(room_id.to_string())
  .fetch_one(pool)
  .await
  .context("failed to read max event sequence")?;

  let max: i64 = row.try_get("max_seq").unwrap_or(0);
  Ok(max as u64)
}

fn parse_event_row(row: SqliteRow) -> Result<RoomEvent> {
  let room_id_str: String = row
    .try_get("room_id")
    .context("room_events.room_id missing")?;
  let room_id: Uuid = room_id_str
    .parse()
    .context("room_events.room_id not a uuid")?;
  let sequence: i64 = row
    .try_get("sequence")
    .context("room_events.sequence missing")?;
  let kind_str: String =
    row.try_get("kind").context("room_events.kind missing")?;
  let tool_calls_json: String = row
    .try_get("tool_calls")
    .context("room_events.tool_calls missing")?;
  let tool_calls = serde_json::from_str(&tool_calls_json)
    .context("room_events.tool_calls invalid JSON")?;

  Ok(RoomEvent {
    room_id,
    sequence: sequence as u64,
    kind: RoomEventKind::parse(&kind_str)?,
    agent: row.try_get("agent").context("room_events.agent missing")?,
    content: row
      .try_get("content")
      .context("room_events.content missing")?,
    reasoning: row
      .try_get("reasoning")
      .context("room_events.reasoning missing")?,
    tool_calls,
    timestamp: parse_timestamp(&row, "timestamp")?,
  })
}

// -- Reports ---------------------------------------------------------------

/// Inserts an empty report row in the `Streaming` state and returns the new
/// row. Subsequent calls to [`finish_report`] flip `status` and persist the
/// final content.
pub async fn start_report(
  pool: &SqlitePool,
  room_id: Uuid,
  sequence: u64,
  started_at: DateTime<Utc>,
) -> Result<RoomReport> {
  let result = sqlx::query(
    "INSERT INTO room_reports
        (room_id, sequence, content, started_at, completed_at, status)
     VALUES (?, ?, ?, ?, NULL, ?)",
  )
  .bind(room_id.to_string())
  .bind(sequence as i64)
  .bind("")
  .bind(started_at.to_rfc3339())
  .bind(ReportStatus::Streaming.as_str())
  .execute(pool)
  .await
  .context("failed to start report")?;

  Ok(RoomReport {
    id: result.last_insert_rowid(),
    room_id,
    sequence,
    content: String::new(),
    started_at,
    completed_at: None,
    status: ReportStatus::Streaming,
  })
}

/// Finalizes a previously-started report with its full body and a terminal
/// status. The `id` is the auto-increment primary key returned by
/// [`start_report`].
pub async fn finish_report(
  pool: &SqlitePool,
  id: i64,
  content: &str,
  status: ReportStatus,
  completed_at: DateTime<Utc>,
) -> Result<()> {
  sqlx::query(
    "UPDATE room_reports
     SET content = ?, status = ?, completed_at = ?
     WHERE id = ?",
  )
  .bind(content)
  .bind(status.as_str())
  .bind(completed_at.to_rfc3339())
  .bind(id)
  .execute(pool)
  .await
  .context("failed to finish report")?;
  Ok(())
}

pub async fn load_room_reports(
  pool: &SqlitePool,
  room_id: Uuid,
) -> Result<Vec<RoomReport>> {
  let rows = sqlx::query(
    "SELECT id, room_id, sequence, content, started_at, completed_at, status
     FROM room_reports WHERE room_id = ? ORDER BY sequence ASC",
  )
  .bind(room_id.to_string())
  .fetch_all(pool)
  .await
  .context("failed to load room reports")?;

  rows.into_iter().map(parse_report_row).collect()
}

pub async fn load_room_report(
  pool: &SqlitePool,
  room_id: Uuid,
  sequence: u64,
) -> Result<Option<RoomReport>> {
  let row = sqlx::query(
    "SELECT id, room_id, sequence, content, started_at, completed_at, status
     FROM room_reports WHERE room_id = ? AND sequence = ?",
  )
  .bind(room_id.to_string())
  .bind(sequence as i64)
  .fetch_optional(pool)
  .await
  .context("failed to load room report")?;

  row.map(parse_report_row).transpose()
}

pub async fn max_report_sequence(
  pool: &SqlitePool,
  room_id: Uuid,
) -> Result<u64> {
  let row = sqlx::query(
    "SELECT COALESCE(MAX(sequence), 0) AS max_seq
     FROM room_reports WHERE room_id = ?",
  )
  .bind(room_id.to_string())
  .fetch_one(pool)
  .await
  .context("failed to read max report sequence")?;

  let max: i64 = row.try_get("max_seq").unwrap_or(0);
  Ok(max as u64)
}

fn parse_report_row(row: SqliteRow) -> Result<RoomReport> {
  let room_id_str: String = row
    .try_get("room_id")
    .context("room_reports.room_id missing")?;
  let room_id: Uuid = room_id_str
    .parse()
    .context("room_reports.room_id not a uuid")?;
  let sequence: i64 = row
    .try_get("sequence")
    .context("room_reports.sequence missing")?;
  let status_str: String = row
    .try_get("status")
    .context("room_reports.status missing")?;
  let status = ReportStatus::parse(&status_str)?;
  let completed_at_str: Option<String> = row
    .try_get("completed_at")
    .context("room_reports.completed_at missing")?;

  let completed_at = match completed_at_str {
    Some(value) => Some(parse_rfc3339(&value)?),
    None => None,
  };

  Ok(RoomReport {
    id: row.try_get("id").context("room_reports.id missing")?,
    room_id,
    sequence: sequence as u64,
    content: row
      .try_get("content")
      .context("room_reports.content missing")?,
    started_at: parse_timestamp(&row, "started_at")?,
    completed_at,
    status,
  })
}

// -- Helpers ---------------------------------------------------------------

fn parse_timestamp(row: &SqliteRow, column: &str) -> Result<DateTime<Utc>> {
  let raw: String = row
    .try_get(column)
    .with_context(|| format!("{column}: missing"))?;
  parse_rfc3339(&raw)
}

fn parse_rfc3339(raw: &str) -> Result<DateTime<Utc>> {
  let parsed = DateTime::parse_from_rfc3339(raw)
    .with_context(|| format!("not an RFC3339 timestamp: {raw}"))?;
  Ok(parsed.with_timezone(&Utc))
}
