//! SQLite persistence layer.
//!
//! All database access goes through this module. Functions in this file are
//! intentionally low-level: they take/return domain types from
//! [`crate::models`] and translate to/from SQLite rows. They do not know
//! about app state, broadcast channels, or LLM behavior.
//!
//! Sequence numbers (`room_events.sequence`, `room_reports.sequence`) are
//! generated by callers (the orchestrator owns an in-memory counter per
//! room). On orchestrator startup, [`max_event_sequence`] and
//! [`max_report_sequence`] seed those counters.

use crate::models::{
  AppSettings, DebateState, ProviderConfig, Room, RoomEvent, RoomEventKind,
  RoomReport, RoomState,
};
use anyhow::{Context, Result};
use chrono::{DateTime, Utc};
use sqlx::Row;
use sqlx::sqlite::{
  SqliteConnectOptions, SqliteJournalMode, SqlitePoolOptions,
};
use sqlx::{SqlitePool, sqlite::SqliteRow};

// -- Pool ------------------------------------------------------------------

/// Opens (or creates) the SQLite database, runs migrations, and returns the
/// pool. The pool's max connection count is small because all writes
/// originate from the orchestrator and a handful of API handlers.
pub async fn init_pool(database_url: &str) -> Result<SqlitePool> {
  let options = database_url
    .parse::<SqliteConnectOptions>()
    .context("invalid DATABASE_URL")?
    .journal_mode(SqliteJournalMode::Wal)
    .foreign_keys(true)
    .create_if_missing(true);

  let pool = SqlitePoolOptions::new()
    .max_connections(5)
    .connect_with(options)
    .await
    .context("failed to connect to SQLite database")?;

  sqlx::migrate!("./migrations")
    .run(&pool)
    .await
    .context("failed to run database migrations")?;

  Ok(pool)
}

// -- Rooms -----------------------------------------------------------------

/// Inserts a new room. Fails if a room with the same `code` already exists.
pub async fn insert_room(pool: &SqlitePool, room: &Room) -> Result<()> {
  sqlx::query(
    "INSERT INTO rooms (
        code, topic, goal, instruction, room_state, debate_state,
        chat_interval_seconds, steering_interval_seconds,
        report_schedule_cron, report_schedule_label,
        python_timeout_seconds,
        resume_schedule_cron, resume_schedule_label,
        created_at, updated_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
  )
  .bind(&room.code)
  .bind(&room.topic)
  .bind(&room.goal)
  .bind(room.instruction.as_deref())
  .bind(room.room_state.as_str())
  .bind(room.debate_state.as_str())
  .bind(room.chat_interval_seconds as i64)
  .bind(room.steering_interval_seconds as i64)
  .bind(&room.report_schedule_cron)
  .bind(&room.report_schedule_label)
  .bind(room.python_timeout_seconds as i64)
  .bind(&room.resume_schedule_cron)
  .bind(&room.resume_schedule_label)
  .bind(room.created_at.to_rfc3339())
  .bind(room.updated_at.to_rfc3339())
  .execute(pool)
  .await
  .context("failed to insert room")?;

  Ok(())
}

/// Replaces every mutable field of an existing room. The orchestrator does
/// not call this directly — only the `PATCH /v1/rooms/:code` handler does.
pub async fn update_room(pool: &SqlitePool, room: &Room) -> Result<()> {
  sqlx::query(
    "UPDATE rooms SET
        topic = ?, goal = ?, instruction = ?,
        room_state = ?, debate_state = ?,
        chat_interval_seconds = ?, steering_interval_seconds = ?,
        report_schedule_cron = ?, report_schedule_label = ?,
        python_timeout_seconds = ?,
        resume_schedule_cron = ?, resume_schedule_label = ?,
        updated_at = ?
     WHERE code = ?",
  )
  .bind(&room.topic)
  .bind(&room.goal)
  .bind(room.instruction.as_deref())
  .bind(room.room_state.as_str())
  .bind(room.debate_state.as_str())
  .bind(room.chat_interval_seconds as i64)
  .bind(room.steering_interval_seconds as i64)
  .bind(&room.report_schedule_cron)
  .bind(&room.report_schedule_label)
  .bind(room.python_timeout_seconds as i64)
  .bind(&room.resume_schedule_cron)
  .bind(&room.resume_schedule_label)
  .bind(room.updated_at.to_rfc3339())
  .bind(&room.code)
  .execute(pool)
  .await
  .context("failed to update room")?;

  Ok(())
}

/// Updates the user-controlled [`RoomState`] gate (`active` /
/// `deactivated`) and `updated_at`. Used by the user-facing
/// `/v1/rooms/:code/activate` and `/deactivate` endpoints.
pub async fn update_room_state(
  pool: &SqlitePool,
  room_code: &str,
  state: RoomState,
  updated_at: DateTime<Utc>,
) -> Result<()> {
  sqlx::query("UPDATE rooms SET room_state = ?, updated_at = ? WHERE code = ?")
    .bind(state.as_str())
    .bind(updated_at.to_rfc3339())
    .bind(room_code)
    .execute(pool)
    .await
    .context("failed to update room_state")?;
  Ok(())
}

/// Updates the leader-controlled [`DebateState`] gate (`running` /
/// `paused`) and `updated_at`. Used by `pause_room` / `resume_room`.
pub async fn update_debate_state(
  pool: &SqlitePool,
  room_code: &str,
  state: DebateState,
  updated_at: DateTime<Utc>,
) -> Result<()> {
  sqlx::query(
    "UPDATE rooms SET debate_state = ?, updated_at = ? WHERE code = ?",
  )
  .bind(state.as_str())
  .bind(updated_at.to_rfc3339())
  .bind(room_code)
  .execute(pool)
  .await
  .context("failed to update debate_state")?;
  Ok(())
}

/// Deletes a room and all of its events/reports (FK cascade).
pub async fn delete_room(pool: &SqlitePool, room_code: &str) -> Result<()> {
  sqlx::query("DELETE FROM rooms WHERE code = ?")
    .bind(room_code)
    .execute(pool)
    .await
    .context("failed to delete room")?;
  Ok(())
}

pub async fn load_all_rooms(pool: &SqlitePool) -> Result<Vec<Room>> {
  let rows = sqlx::query("SELECT * FROM rooms ORDER BY created_at DESC")
    .fetch_all(pool)
    .await
    .context("failed to load rooms")?;

  rows.into_iter().map(parse_room_row).collect()
}

/// Returns true if the given code is already taken. Used by room creation
/// to retry generation in the (vanishingly rare) case of a collision.
pub async fn code_taken(pool: &SqlitePool, code: &str) -> Result<bool> {
  let row = sqlx::query("SELECT 1 AS taken FROM rooms WHERE code = ? LIMIT 1")
    .bind(code)
    .fetch_optional(pool)
    .await
    .context("failed to check code uniqueness")?;
  Ok(row.is_some())
}

fn parse_room_row(row: SqliteRow) -> Result<Room> {
  let room_state_str: String = row
    .try_get("room_state")
    .context("rooms.room_state missing")?;
  let room_state = RoomState::parse(&room_state_str)?;
  let debate_state_str: String = row
    .try_get("debate_state")
    .context("rooms.debate_state missing")?;
  let debate_state = DebateState::parse(&debate_state_str)?;

  let chat_interval: i64 = row
    .try_get("chat_interval_seconds")
    .context("rooms.chat_interval_seconds missing")?;
  let steering_interval: i64 = row
    .try_get("steering_interval_seconds")
    .context("rooms.steering_interval_seconds missing")?;
  let python_timeout: i64 = row
    .try_get("python_timeout_seconds")
    .context("rooms.python_timeout_seconds missing")?;

  Ok(Room {
    code: row.try_get("code").context("rooms.code missing")?,
    topic: row.try_get("topic").context("rooms.topic missing")?,
    goal: row.try_get("goal").context("rooms.goal missing")?,
    instruction: row
      .try_get("instruction")
      .context("rooms.instruction missing")?,
    room_state,
    debate_state,
    chat_interval_seconds: chat_interval as u64,
    steering_interval_seconds: steering_interval as u64,
    report_schedule_cron: row
      .try_get("report_schedule_cron")
      .context("rooms.report_schedule_cron missing")?,
    report_schedule_label: row
      .try_get("report_schedule_label")
      .context("rooms.report_schedule_label missing")?,
    python_timeout_seconds: python_timeout as u64,
    resume_schedule_cron: row
      .try_get("resume_schedule_cron")
      .context("rooms.resume_schedule_cron missing")?,
    resume_schedule_label: row
      .try_get("resume_schedule_label")
      .context("rooms.resume_schedule_label missing")?,
    created_at: parse_timestamp(&row, "created_at")?,
    updated_at: parse_timestamp(&row, "updated_at")?,
  })
}

// -- App settings ----------------------------------------------------------

/// Loads the singleton `app_settings` row. The migration always seeds row 1,
/// so this either returns the user's saved settings or the empty
/// placeholder.
pub async fn load_app_settings(pool: &SqlitePool) -> Result<AppSettings> {
  let row = sqlx::query(
    "SELECT low_provider_config, high_provider_config, updated_at
     FROM app_settings WHERE id = 1",
  )
  .fetch_one(pool)
  .await
  .context("failed to load app settings")?;

  let low_json: String = row
    .try_get("low_provider_config")
    .context("app_settings.low_provider_config missing")?;
  let high_json: String = row
    .try_get("high_provider_config")
    .context("app_settings.high_provider_config missing")?;
  let low: ProviderConfig = serde_json::from_str(&low_json)
    .context("app_settings.low_provider_config: invalid JSON")?;
  let high: ProviderConfig = serde_json::from_str(&high_json)
    .context("app_settings.high_provider_config: invalid JSON")?;

  Ok(AppSettings {
    low,
    high,
    updated_at: parse_timestamp(&row, "updated_at")?,
  })
}

/// Persists the singleton `app_settings` row. Caller has already validated
/// both provider configs and resolved any redacted-key sentinels.
pub async fn update_app_settings(
  pool: &SqlitePool,
  settings: &AppSettings,
) -> Result<()> {
  let low_json = serde_json::to_string(&settings.low)
    .context("failed to encode low provider config")?;
  let high_json = serde_json::to_string(&settings.high)
    .context("failed to encode high provider config")?;

  sqlx::query(
    "UPDATE app_settings
     SET low_provider_config = ?, high_provider_config = ?, updated_at = ?
     WHERE id = 1",
  )
  .bind(&low_json)
  .bind(&high_json)
  .bind(settings.updated_at.to_rfc3339())
  .execute(pool)
  .await
  .context("failed to update app settings")?;
  Ok(())
}

// -- Events ----------------------------------------------------------------

/// Inserts a row at the start of its lifecycle. Streaming rows start with
/// `success = false` and `completed_at = None`; [`finish_event`] stamps
/// `completed_at` and sets `success` when the row is done. Pre-finalized
/// rows (e.g. user messages) are inserted with `success = true` and a
/// matching `completed_at`.
pub async fn insert_event(
  pool: &SqlitePool,
  event: &RoomEvent,
) -> Result<RoomEvent> {
  let result = sqlx::query(
    "INSERT INTO room_events
        (room_code, sequence, kind, agent, content, detail, success, timestamp, completed_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
  )
  .bind(&event.room_code)
  .bind(event.sequence as i64)
  .bind(event.kind.as_str())
  .bind(event.agent.as_deref())
  .bind(&event.content)
  .bind(&event.detail)
  .bind(event.success)
  .bind(event.timestamp.to_rfc3339())
  .bind(event.completed_at.map(|t| t.to_rfc3339()))
  .execute(pool)
  .await
  .context("failed to insert room event")?;
  let mut stored = event.clone();
  stored.id = Some(result.last_insert_rowid());
  Ok(stored)
}

/// Replaces `content` and `detail` for a streaming row. Cheap enough to
/// call on every flush tick because SQLite WAL absorbs the writes.
pub async fn update_event_body(
  pool: &SqlitePool,
  id: i64,
  content: &str,
  detail: &str,
) -> Result<()> {
  sqlx::query("UPDATE room_events SET content = ?, detail = ? WHERE id = ?")
    .bind(content)
    .bind(detail)
    .bind(id)
    .execute(pool)
    .await
    .context("failed to update room event body")?;
  Ok(())
}

/// Finalizes a streaming row: stamps the body one last time, sets `success`,
/// and records `completed_at`.
pub async fn finish_event(
  pool: &SqlitePool,
  id: i64,
  content: &str,
  detail: &str,
  success: bool,
  completed_at: DateTime<Utc>,
) -> Result<()> {
  sqlx::query(
    "UPDATE room_events
     SET content = ?, detail = ?, success = ?, completed_at = ?
     WHERE id = ?",
  )
  .bind(content)
  .bind(detail)
  .bind(success)
  .bind(completed_at.to_rfc3339())
  .bind(id)
  .execute(pool)
  .await
  .context("failed to finish room event")?;
  Ok(())
}

/// Closes any rows left open (completed_at IS NULL) from a previous run.
/// Called when a room loop starts so stale streaming rows don't linger.
pub async fn close_incomplete_events(
  pool: &SqlitePool,
  room_code: &str,
) -> Result<()> {
  let now = Utc::now().to_rfc3339();
  sqlx::query(
    "UPDATE room_events
     SET completed_at = ?, success = 0
     WHERE room_code = ? AND completed_at IS NULL",
  )
  .bind(now)
  .bind(room_code)
  .execute(pool)
  .await
  .context("failed to close incomplete events")?;
  Ok(())
}

pub async fn load_room_events(
  pool: &SqlitePool,
  room_code: &str,
) -> Result<Vec<RoomEvent>> {
  let rows = sqlx::query(
    "SELECT id, room_code, sequence, kind, agent, content, detail, success, timestamp, completed_at
     FROM room_events
     WHERE room_code = ?
     ORDER BY sequence ASC",
  )
  .bind(room_code)
  .fetch_all(pool)
  .await
  .context("failed to load room events")?;

  rows.into_iter().map(parse_event_row).collect()
}

/// Loads a single room-event row by its per-room sequence number. Used by
/// the `get_room_event` tool and the REST endpoint so agents and the frontend
/// can retrieve any event that may have been compacted out of the live
/// transcript.
pub async fn load_room_event(
  pool: &SqlitePool,
  room_code: &str,
  sequence: i64,
) -> Result<Option<RoomEvent>> {
  let row = sqlx::query(
    "SELECT id, room_code, sequence, kind, agent, content, detail, success, timestamp, completed_at
     FROM room_events
     WHERE room_code = ? AND sequence = ?",
  )
  .bind(room_code)
  .bind(sequence)
  .fetch_optional(pool)
  .await
  .context("failed to load room event")?;
  row.map(parse_event_row).transpose()
}

/// Returns the latest `Summary` event for the given room, or `None` if no
/// compaction has run yet. Used by the history loader to find the cutoff
/// point beyond which events are loaded verbatim.
pub async fn load_compaction_checkpoint(
  pool: &SqlitePool,
  room_code: &str,
) -> Result<Option<RoomEvent>> {
  let row = sqlx::query(
    "SELECT id, room_code, sequence, kind, agent, content, detail, success, timestamp, completed_at
     FROM room_events
     WHERE room_code = ? AND kind = 'summary'
     ORDER BY sequence DESC
     LIMIT 1",
  )
  .bind(room_code)
  .fetch_optional(pool)
  .await
  .context("failed to load compaction checkpoint")?;
  row.map(parse_event_row).transpose()
}

/// Returns all events for the given room with `sequence` strictly greater
/// than `after_sequence`, in ascending sequence order. Used to load only
/// the tail after a compaction checkpoint.
pub async fn load_room_events_after(
  pool: &SqlitePool,
  room_code: &str,
  after_sequence: u64,
) -> Result<Vec<RoomEvent>> {
  let rows = sqlx::query(
    "SELECT id, room_code, sequence, kind, agent, content, detail, success, timestamp, completed_at
     FROM room_events
     WHERE room_code = ? AND sequence > ?
     ORDER BY sequence ASC",
  )
  .bind(room_code)
  .bind(after_sequence as i64)
  .fetch_all(pool)
  .await
  .context("failed to load room events after sequence")?;
  rows.into_iter().map(parse_event_row).collect()
}

/// Returns the highest `sequence` for the given room, or 0 if the room has
/// no events yet. Used to seed the orchestrator's per-room counter on
/// startup.
pub async fn max_event_sequence(
  pool: &SqlitePool,
  room_code: &str,
) -> Result<u64> {
  let row = sqlx::query(
    "SELECT COALESCE(MAX(sequence), 0) AS max_seq
     FROM room_events WHERE room_code = ?",
  )
  .bind(room_code)
  .fetch_one(pool)
  .await
  .context("failed to read max event sequence")?;

  let max: i64 = row.try_get("max_seq").unwrap_or(0);
  Ok(max as u64)
}

fn parse_event_row(row: SqliteRow) -> Result<RoomEvent> {
  let id: i64 = row.try_get("id").context("room_events.id missing")?;
  let sequence: i64 = row
    .try_get("sequence")
    .context("room_events.sequence missing")?;
  let kind_str: String =
    row.try_get("kind").context("room_events.kind missing")?;
  let success: bool = row
    .try_get("success")
    .context("room_events.success missing")?;
  let completed_at_str: Option<String> = row
    .try_get("completed_at")
    .context("room_events.completed_at missing")?;
  let completed_at = match completed_at_str {
    Some(value) => Some(parse_rfc3339(&value)?),
    None => None,
  };

  Ok(RoomEvent {
    id: Some(id),
    room_code: row
      .try_get("room_code")
      .context("room_events.room_code missing")?,
    sequence: sequence as u64,
    kind: RoomEventKind::parse(&kind_str)?,
    agent: row.try_get("agent").context("room_events.agent missing")?,
    content: row
      .try_get("content")
      .context("room_events.content missing")?,
    detail: row
      .try_get("detail")
      .context("room_events.detail missing")?,
    success,
    timestamp: parse_timestamp(&row, "timestamp")?,
    completed_at,
  })
}

// -- Reports ---------------------------------------------------------------

/// Inserts an empty report row in the `Streaming` state and returns the new
/// row. Subsequent calls to [`finish_report`] flip `status` and persist the
/// final content.
pub async fn start_report(
  pool: &SqlitePool,
  room_code: &str,
  sequence: u64,
  started_at: DateTime<Utc>,
) -> Result<RoomReport> {
  let result = sqlx::query(
    "INSERT INTO room_reports
        (room_code, sequence, content, started_at, completed_at, success)
     VALUES (?, ?, ?, ?, NULL, ?)",
  )
  .bind(room_code)
  .bind(sequence as i64)
  .bind("")
  .bind(started_at.to_rfc3339())
  .bind(false)
  .execute(pool)
  .await
  .context("failed to start report")?;

  Ok(RoomReport {
    id: result.last_insert_rowid(),
    room_code: room_code.to_string(),
    sequence,
    content: String::new(),
    started_at,
    completed_at: None,
    success: false,
  })
}

/// Finalizes a previously-started report with its full body and a terminal
/// status. The `id` is the auto-increment primary key returned by
/// [`start_report`].
pub async fn finish_report(
  pool: &SqlitePool,
  id: i64,
  content: &str,
  success: bool,
  completed_at: DateTime<Utc>,
) -> Result<()> {
  sqlx::query(
    "UPDATE room_reports
     SET content = ?, success = ?, completed_at = ?
     WHERE id = ?",
  )
  .bind(content)
  .bind(success)
  .bind(completed_at.to_rfc3339())
  .bind(id)
  .execute(pool)
  .await
  .context("failed to finish report")?;
  Ok(())
}

pub async fn load_room_reports(
  pool: &SqlitePool,
  room_code: &str,
) -> Result<Vec<RoomReport>> {
  let rows = sqlx::query(
    "SELECT id, room_code, sequence, content, started_at, completed_at, success
     FROM room_reports WHERE room_code = ? ORDER BY sequence ASC",
  )
  .bind(room_code)
  .fetch_all(pool)
  .await
  .context("failed to load room reports")?;

  rows.into_iter().map(parse_report_row).collect()
}

pub async fn load_room_report(
  pool: &SqlitePool,
  room_code: &str,
  sequence: u64,
) -> Result<Option<RoomReport>> {
  let row = sqlx::query(
    "SELECT id, room_code, sequence, content, started_at, completed_at, success
     FROM room_reports WHERE room_code = ? AND sequence = ?",
  )
  .bind(room_code)
  .bind(sequence as i64)
  .fetch_optional(pool)
  .await
  .context("failed to load room report")?;

  row.map(parse_report_row).transpose()
}

pub async fn max_report_sequence(
  pool: &SqlitePool,
  room_code: &str,
) -> Result<u64> {
  let row = sqlx::query(
    "SELECT COALESCE(MAX(sequence), 0) AS max_seq
     FROM room_reports WHERE room_code = ?",
  )
  .bind(room_code)
  .fetch_one(pool)
  .await
  .context("failed to read max report sequence")?;

  let max: i64 = row.try_get("max_seq").unwrap_or(0);
  Ok(max as u64)
}

fn parse_report_row(row: SqliteRow) -> Result<RoomReport> {
  let sequence: i64 = row
    .try_get("sequence")
    .context("room_reports.sequence missing")?;
  let success: bool = row
    .try_get("success")
    .context("room_reports.success missing")?;
  let completed_at_str: Option<String> = row
    .try_get("completed_at")
    .context("room_reports.completed_at missing")?;

  let completed_at = match completed_at_str {
    Some(value) => Some(parse_rfc3339(&value)?),
    None => None,
  };

  Ok(RoomReport {
    id: row.try_get("id").context("room_reports.id missing")?,
    room_code: row
      .try_get("room_code")
      .context("room_reports.room_code missing")?,
    sequence: sequence as u64,
    content: row
      .try_get("content")
      .context("room_reports.content missing")?,
    started_at: parse_timestamp(&row, "started_at")?,
    completed_at,
    success,
  })
}

// -- Helpers ---------------------------------------------------------------

fn parse_timestamp(row: &SqliteRow, column: &str) -> Result<DateTime<Utc>> {
  let raw: String = row
    .try_get(column)
    .with_context(|| format!("{column}: missing"))?;
  parse_rfc3339(&raw)
}

fn parse_rfc3339(raw: &str) -> Result<DateTime<Utc>> {
  let parsed = DateTime::parse_from_rfc3339(raw)
    .with_context(|| format!("not an RFC3339 timestamp: {raw}"))?;
  Ok(parsed.with_timezone(&Utc))
}
