//! WebSocket wire protocol for room event streams.
//!
//! All messages a client receives over `/v1/rooms/:id/stream` are JSON
//! encodings of [`WsEvent`]. The `type` discriminator lets the frontend
//! pattern-match on a single union.
//!
//! Streaming-only events (`turn_token`, `report_token`) are *not* persisted.
//! They exist purely so the frontend can render token deltas live; the
//! authoritative record is the matching `_completed` event plus the database
//! rows replayed via [`WsEvent::Snapshot`] on connect.

use crate::models::{
  ReportStatus, RoomEvent, RoomReport, RoomStatus, RoomView,
};
use chrono::{DateTime, Utc};
use serde::Serialize;
use uuid::Uuid;

/// Identifier of an in-flight turn, generated by the orchestrator.
///
/// Frontends key their per-token rendering buffer on this id and discard it
/// when the matching `TurnCompleted` (or `TurnFailed`) arrives.
pub type TurnId = String;

/// Identifier of an in-flight report row in the WS stream. While a report
/// is streaming, we use a stable string so the frontend can attach token
/// deltas; the value mirrors the database `id` for finalized reports.
pub type ReportId = String;

/// One frame of the WebSocket wire format. Variants are tagged with `type`
/// in the JSON output, e.g. `{"type":"turnToken","turnId":"...","delta":"hi"}`.
///
/// `Snapshot` carries `RoomView` boxed because it dwarfs every other
/// variant in size and would otherwise inflate the per-event allocation
/// for token streams.
#[derive(Debug, Clone, Serialize)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum WsEvent {
  /// First message after a successful connect. Contains the room's current
  /// settings, the persisted history, and any in-flight turn the
  /// orchestrator was already streaming.
  Snapshot {
    room: Box<RoomView>,
    events: Vec<RoomEvent>,
    reports: Vec<RoomReport>,
  },

  /// Room lifecycle change: active <-> paused, or terminal failure.
  RoomStatus { status: RoomStatus },

  /// A new turn has started. Token deltas with the same `turn_id` follow.
  TurnStarted {
    turn_id: TurnId,
    agent: String,
    kind: TurnKind,
  },
  /// One token (or partial token) of the in-flight turn's natural-language
  /// content. The frontend appends `delta` to the buffer keyed by `turn_id`.
  TurnToken { turn_id: TurnId, delta: String },
  /// The turn finished cleanly. The full `content` is the authoritative
  /// payload; the frontend may discard the per-token buffer once received.
  TurnCompleted {
    turn_id: TurnId,
    sequence: u64,
    agent: String,
    content: String,
    timestamp: DateTime<Utc>,
  },
  /// The turn ended in error. `partial` contains whatever was streamed
  /// successfully before the failure; `error` is a human-readable message.
  TurnFailed {
    turn_id: TurnId,
    partial: String,
    error: String,
  },

  /// A tool invocation has begun. Tool execution is opaque to other agents
  /// — only the calling agent sees the result — but the UI displays it as a
  /// labeled card so the user can follow what's happening.
  ToolStarted {
    turn_id: TurnId,
    tool: String,
    args_preview: String,
  },
  /// A tool invocation finished. `ok = false` means it errored; the output
  /// preview is truncated to keep the WS payload compact.
  ToolCompleted {
    turn_id: TurnId,
    sequence: u64,
    tool: String,
    ok: bool,
    output_preview: String,
    duration_ms: u64,
    timestamp: DateTime<Utc>,
  },

  /// A periodic leader report has begun streaming.
  ReportStarted { report_id: ReportId, sequence: u64 },
  /// One token of the in-flight report.
  ReportToken { report_id: ReportId, delta: String },
  /// The report finished. The persisted row is replayed via the snapshot on
  /// reconnect; the live event carries enough to render immediately.
  ReportCompleted {
    report_id: ReportId,
    sequence: u64,
    content: String,
    status: ReportStatus,
    completed_at: DateTime<Utc>,
  },
}

/// Categorization of a turn for the UI. Drives the visual treatment (chat
/// bubble vs. leader callout) without leaking transcript-shape details.
#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum TurnKind {
  /// A debater (low-model persona) speaking.
  AgentChat,
  /// A leader steering note triggered by the periodic evaluation timer or
  /// the `request_leader_decision` tool.
  LeaderNote,
}

/// Builds a fresh, unique [`TurnId`] for a new turn. Wraps a random UUID so
/// no caller has to think about uniqueness.
pub fn new_turn_id() -> TurnId {
  Uuid::new_v4().to_string()
}

/// Builds a [`ReportId`] for an in-flight report. Once the report is
/// persisted, the same string (the row's database id) is used in
/// [`WsEvent::ReportCompleted`].
pub fn report_id_for(database_id: i64) -> ReportId {
  database_id.to_string()
}
