/**
 * Chat-rendering helpers shared by the message bubble and the page that
 * lays bubbles out (avatar grouping, time-gap separators, persona color
 * assignment).
 *
 * The color assignment is deterministic: the same agent name always maps
 * to the same palette slot so a persona keeps its identity across rooms,
 * across reloads, and even after server-side renames.
 */

import type { RoomEventKind } from "@/app/types";

/** Stable string the backend writes into `agent` for human-authored rows. */
export const USER_AGENT_NAME = "user";

/** Time gap (ms) at or above which the chat shows a centered timestamp. */
export const TIME_GAP_THRESHOLD_MS = 5 * 60 * 1000;

export interface PersonaColor {
  /** Background fill for the avatar circle. */
  background: string;
  /** Text/icon color drawn on top of the background. */
  foreground: string;
}

/**
 * 32-slot palette generated by evenly spacing OKLCH hues (0-360 deg in 11.25
 * deg steps). OKLCH is perceptually uniform so each slot looks equally saturated
 * and bright, giving distinct identities at the small avatar size.
 */
const PALETTE: PersonaColor[] = Array.from({ length: 32 }, (_, i) => ({
  background: `oklch(0.68 0.18 ${((i * 360) / 32).toFixed(2)})`,
  foreground: "#1a1a1a",
}));

/** Brand color used for the human operator's own messages. */
const SELF_COLOR: PersonaColor = {
  background: "var(--wa-color-brand-fill-loud)",
  foreground: "var(--wa-color-brand-on-loud)",
};

/**
 * Resolves the avatar color for one chat row. `user_chat` always returns
 * the brand color so the human's identity is never mistaken for an AI
 * persona, even if some persona happened to be named "user".
 */
export function resolveAvatarColor(
  kind: RoomEventKind,
  agent: string | null,
): PersonaColor {
  if (kind === "user_chat") {
    return SELF_COLOR;
  }
  const key = agent ?? "";
  if (key === "") {
    return PALETTE[0];
  }
  return PALETTE[hashToIndex(key, PALETTE.length)];
}

/**
 * Returns true when the chat should insert a centered timestamp separator
 * between `previous` and `current`. First message always gets one; later
 * separators only appear when the gap exceeds [`TIME_GAP_THRESHOLD_MS`].
 */
export function shouldShowTimeSeparator(
  previousTimestamp: string | null,
  currentTimestamp: string,
): boolean {
  if (previousTimestamp === null) {
    return true;
  }
  const previous = Date.parse(previousTimestamp);
  const current = Date.parse(currentTimestamp);
  if (Number.isNaN(previous) || Number.isNaN(current)) {
    return false;
  }
  return current - previous >= TIME_GAP_THRESHOLD_MS;
}

/**
 * Formats a timestamp the way the centered separator displays it. We keep
 * the date out unless the message is from a different day than "now",
 * matching how Instagram/KakaoTalk lay out their separators.
 */
export function formatSeparatorTimestamp(timestamp: string): string {
  const when = new Date(timestamp);
  return when.toLocaleString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

/**
 * Formats a millisecond duration as a compact `Ns` / `M:SS` string. The
 * dialog uses the same format for the final "Took N seconds" line, so
 * elapsed labels look identical pre/post finalisation.
 */
export function formatDuration(milliseconds: number): string {
  const totalSeconds = Math.max(0, Math.floor(milliseconds / 1000));
  if (totalSeconds < 60) {
    return `${totalSeconds}s`;
  }
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  const pad2 = (n: number): string => n < 10 ? `0${n}` : `${n}`;
  return `${minutes}:${pad2(seconds)}`;
}

/**
 * Tiny djb2 string hash, mapped into `[0, modulus)`. Only used for picking
 * a palette slot; collisions are fine because two personas with the same
 * color is purely cosmetic.
 */
function hashToIndex(value: string, modulus: number): number {
  let hash = 5381;
  for (let i = 0; i < value.length; i += 1) {
    hash = ((hash << 5) + hash + value.charCodeAt(i)) | 0;
  }
  return Math.abs(hash) % modulus;
}
